# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      framework-ecosystem:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react*'
          - '@types/node'
          - 'next'
          - 'eslint-config-next'
          - '@payloadcms/*'
          - 'cross-env'
          - 'dotenv'
          - 'graphql'
          - 'sharp'
          - 'typescript'
        update-types:
          - 'minor'
          - 'patch'
      testing-ecosystem:
        patterns:
          - '@playwright/*'
          - 'playwright*'
          - 'vitest'
          - '@testing-library/*'
          - '@vitejs/plugin-react'
          - 'jsdom'
          - 'vite-tsconfig-paths'
        update-types:
          - 'minor'
          - 'patch'
      styling-ecosystem:
        patterns:
          - 'tailwindcss'
          - '@tailwindcss/*'
          - 'postcss'
          - 'prettier-plugin-tailwindcss'
          - 'classnames'
        update-types:
          - 'minor'
          - 'patch'
      linting-formatting:
        patterns:
          - '@eslint/*'
          - 'eslint*'
          - 'prettier*'
        update-types:
          - 'minor'
          - 'patch'
      type-definitions:
        patterns:
          - '@types/*'
        update-types:
          - 'minor'
          - 'patch'
      component-libraries:
        patterns:
          - 'lucide-react'
        update-types:
          - 'minor'
          - 'patch'
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
