# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      payloadcms-ecosystem:
        patterns:
          - '@payloadcms/*'
        update-types:
          - 'minor'
          - 'patch'
      react-ecosystem:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react*'
        update-types:
          - 'minor'
          - 'patch'
      nextjs-ecosystem:
        patterns:
          - 'next'
          - 'eslint-config-next'
        update-types:
          - 'minor'
          - 'patch'
      testing-ecosystem:
        patterns:
          - '@playwright/*'
          - 'playwright*'
          - 'vitest'
          - '@testing-library/*'
        update-types:
          - 'minor'
          - 'patch'
      tailwind-ecosystem:
        patterns:
          - 'tailwindcss'
          - '@tailwindcss/*'
          - 'postcss'
          - 'prettier-plugin-tailwindcss'
        update-types:
          - 'minor'
          - 'patch'
      type-definitions:
        patterns:
          - '@types/*'
        update-types:
          - 'minor'
          - 'patch'
      linting-formatting:
        patterns:
          - 'eslint*'
          - 'prettier*'
        update-types:
          - 'minor'
          - 'patch'
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
